name: rss-dl_CI
on: [push]
jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.os }}
 
    steps:
    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Get dependencies
      run: |
        go get github.com/mmcdole/gofeed

    - name: Build
      run: go build -v .

    - name: Upload Unix Artifacts
      if: startsWith(matrix.os, 'ubuntu-')
      uses: actions/upload-artifact@v1
      with:
        name: rss-dl_linux
        path: rss-dl
        
    - name: Upload Windows Artifacts
      if: startsWith(matrix.os, 'windows-')
      uses: actions/upload-artifact@v1
      with:
        name: rss-dl_win64
        path: rss-dl.exe
